### PR TITLE
global distances notebook & example text file

### PR DESCRIPTION
**Pull request by douglase**

### CODE REVIEW

**Comment by douglase** [comment]
@Jashcraf any objections to merging this in?

**Comment by Jashcraf** [comment]
Well it doesn't do a conversion to a poppy optical system - just prints a
list out of distances from a zemax single ray trace, but otherwise I have
no objections

**Comment by douglase** [comment]
is the rest of the code hiding somewhere or did you just do that manually?

**Comment by douglase** [comment]
closing because already PRed in upstream

**Comment by Jashcraf** [comment]
To generate a poppy optical system? I just did it manually

**Pull request closed without merging**
